# data:
#   base_path: "C:/Users/deves/VolumeD/Final Year Project/TestData/AmazonData/FixedGeoPtData/FULL_INDICES_CLEAN-*"
#   features: ["NDVI", "NDMI", "NBR", "CI_red_edge"]
#   geo_col: ".geo"
#   date_col: "date"
#   window_size: 12
#   max_gap: 2        # max allowed missing months
#   test_split: 0.2

# training:
#   batch_size: 32
#   epochs: 30
#   learning_rate: 0.001

# model:
#   lstm_units: 64
#   dropout: 0.2


data:
  base_path: "C:/Users/deves/VolumeD/Final Year Project/TestData/AmazonData/FixedGeoPtData/FULL_INDICES_CLEAN-*"
  features: ["NDVI", "NDMI", "NBR", "CI_red_edge"]
  geo_col: ".geo"
  date_col: "date"
  window_size: 24       # Increased to 24 months (2 years) to capture Multi-Year trends
  max_gap: 1
  test_split: 0.1

training:
  batch_size: 16        # Increased batch size slightly for stability
  epochs: 100           # Increased epochs as detailed features take longer to learn
  learning_rate: 0.001

model:
  lstm_units: 64        # Increased units for better capacity
  dropout: 0.2

